spring:
  application:
    name: mscartoes
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest

# Quando se coloca a porta 0, ele coloca numa porta aleatoria.
# Devemos fazer isso, pois se subimos varias aplicacoes, iriam ficar na mesma porta.
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:admin@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
# instance-id deve ser o nome mais um valor aleatoria, para nao ficarem todas as instancias com o mesmo nome.

mq:
  queues:
    emissao-cartoes: emissao-cartoes

#Configuração para o Actuator, expor todos endpoints
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

logging:
  file:
    name: ./logs/log-file.log